experiment_info:
  # Main algorithm choices
  experiment_name: DDQN-Agent
  agent: rlcycle.dqn_base.agent.DQNBaseAgent
  learner: rlcycle.dqn_base.learner.DQNLearner
  loss: rlcycle.dqn_base.loss.DQNLoss
  action_selector: rlcycle.dqn_base.action_selector.DQNActionSelector
  device: cpu
  log_wandb: True

  # Environment info
  env:
    name: "LunarLander-v2"
    is_atari: False
    is_discrete: True
    max_episode_steps: 300

  # Experiment default arguments:
  total_num_episodes: 2000
  test_interval: 100  # Test every 50 episodes
  test_num: 5  # Number of episodes to test during test phase
  train_render: False  # Render all episode steps
  test_render: True # Render test

defaults:
  - hyper_params: dqn_mnih2015
  - models: dqn