experiment_info:
  # Main algorithm choices
  experiment_name: SAC-Agent
  agent: rlcycle.sac.agent.SACAgent
  learner: rlcycle.sac.learner.SACLearner
  critic_loss: rlcycle.sac.loss.CriticLoss
  actor_loss: rlcycle.sac.loss.PolicyLoss
  action_selector: rlcycle.sac.action_selector.SACActionSelector
  device: cpu
  log_wandb: True

  # Environment info
  env:
    name: LunarLanderContinuous-v2
    max_episode_steps: 300
 
# Experiment default arguments:
  total_num_episodes: 1500
  test_interval: 100  # Test every 50 episodes
  test_num: 5  # Number of episodes to test during test phase
  render_train: True  
  render_test: True


defaults:
 - hyper_params: sac_haarnoja2019
 - models: sac