model:
  class: rlcycle.common.models.value.DuelingDQNModel
  params:
    model_cfg:
      state_dim: undefined
      action_dim: undefined

      linear_features:  # Using this only when not using cnn as backbone
        class: rlcycle.common.models.layers.LinearLayer
        params: 
          input_size: undefined
          output_size: 512
          post_activation_fn: relu 
          
      advantage:
        fc1:
          class: rlcycle.common.models.layers.LinearLayer
          params: 
            input_size: undefined
            output_size: 512
            post_activation_fn: relu
        fc2:
          class: rlcycle.common.models.layers.LinearLayer
          params: 
            input_size: 512
            output_size: undefined
            post_activation_fn: identity

      value:
        fc1:
          class: rlcycle.common.models.layers.LinearLayer
          params: 
            input_size: undefined
            output_size: 512
            post_activation_fn: identity
        fc2:
          class: rlcycle.common.models.layers.LinearLayer
          params: 
            input_size: 512
            output_size: 1
            post_activation_fn: identity