hyper_params:
  batch_size: 64
  replay_buffer_size: 1000000 #
  use_per: False

  # Exploration configs
  eps: 1.0  # epsilon-greedy exploration
  eps_final: 0.01  # minimum epsilon value for exploration
  max_exploration_frame: 100000  # eps = eps_final at most until # steps

  # Others
  update_starting_point: 10000 # update steps when buffer has # experiences stored
  gamma: 0.99
  tau: 0.005
  learning_rate: 0.00025
  q_reg_coeff: 0
  gradient_clip: 10.0
  n_step: 3
  train_freq: 1
